version: '1.0.0'
services:
    postgres_db:
        image: postgres:latest
        ports:
        - 5432:5432
        env_file:
        - postgres_db.env
        volumes:
        - postgres_data:/var/lib/postgresql/data
    search:
        platform: linux/amd64
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes:
            - ./app:/code/app
            - ./repo/LAVIS:/code/LAVIS
        ports:
           - 4000:4000

