services:
  postgres_db:
    image:  pgvector/pgvector:pg16
    ports:
      - 5432:5432
    env_file:
      - env/postgres_db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      env_file:
      - env/mongo_db.env
      volumes:
        - mongo_data:/data/db
volumes:
  postgres_data:
  mongo_data: